# ~/.config/kitty/kitty.conf

# ======================== Tab ========================
map alt+t new_tab
map alt+shift+t new_tab_with_cwd
map alt+q close_tab

map alt+[ move_tab_backward
map alt+] move_tab_forward

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

# --------------------- Tab bar ---------------------

tab_bar_align center
tab_bar_style separator 
tab_separator "  "
tab_title_template "{index}"
active_tab_font_style bold
inactive_tab_background #001319
inactive_tab_foreground #708183
active_tab_foreground  #ffffff
active_tab_background #001319

# ======================== Fonts ========================

# font_family family='AcPlus IBM VGA 9x16'
# font_size 18.0
# text_composition_strategy legacy

font_family family='Flexi IBM VGA True'
font_size 18.0
text_composition_strategy legacy

# font_family family='Fixedsys Core'
# font_size 14.0
# text_composition_strategy legacy

# font_family family='BlexMono Nerd Font' features='cv09'
# font_size 13.0

# font_family family='PragmataPro Mono Liga Regular'
# italic_font family='PragmataPro Mono Liga Italic'
# bold_font family='PragmataPro Mono Liga Bold'
# bold_italic_font family='PragmataPro Mono Liga Bold Italic'
# font_size 15.0

# font_family family='monolisa nerd font' features='calt liga ss02 ss07 ss09 ss11 ss13 ss14 ss16 ss18'
# italic_font family='monolisa nerd font' style=italic features='calt liga ss01 ss07 ss09 ss11 ss13 ss14 ss16 ss18'
# bold_font family='monolisa nerd font' style=bold features='calt liga ss01 ss07  ss09 ss11 ss13 ss14 ss16 ss18'
# bold_italic_font family='monolisa nerd font' style='bold italic' features='calt liga ss01 ss07 ss09 ss11 ss13 ss14 ss16 ss18'
# font_size 12.0

# ======================== Window ========================
enabled_layouts grid,tall:bias=50;full_size=2, *

map alt+enter new_window_with_cwd
map alt+shift+enter new_window
map alt+backspace close_window

map ctrl+[ move_window_backward
map ctrl+] move_window_forward

map alt+r start_resizing_window

map alt+right resize_window narrower
map alt+left resize_window wider
map alt+up resize_window taller
map alt+down resize_window shorter

focus_follows_mouse yes
map alt+f focus_visible_window

inactive_border_color #002731
active_border_color #52676f

# ======================== Misc ========================
scrollback_lines 200000
enable_audio_bell no
hide_window_decorations yes
# initial_window_width 900
# initial_window_height 600
# remember_window_size no

# ======================== Scrolling ========================
map ctrl+up scroll_line_up
map ctrl+down scroll_line_down

# ======================== Theme (Solarized Osaka) ========================
background #001319
foreground #708183
cursor #708183
selection_background #002731
color0 #002731
color8 #002b35
color1 #d01b24
color9 #bd3612
color2 #728905
color10 #465a61
color3 #a57705
color11 #52676f
color4 #2075c7
color12 #708183
color5 #c61b6e
color13 #5856b9
color6 #259185
color14 #81908f
color7 #e9e2cb
color15 #fcf4dc
selection_foreground #001e26
