# ~/.config/kitty/kitty.conf

# ======================== Theme ========================
include ~/.config/kitty/themes/solarized-osaka.conf
#include ~/.config/kitty/themes/kanagawa.conf

# ======================== Fonts ========================
disable_ligatures never
# --------------------- Pragmatapro ---------------------
# font_family pragmatapro mono liga regular
# font_size 13

# --------------------- Monolisa ---------------------
font_family monolisa nerd font
font_family family='monolisa nerd font' features='calt liga ss01 ss07 ss09 ss11 ss14 ss16'
italic_font family='monolisa nerd font' style=italic features='calt liga ss01 ss07 ss09 ss11 ss14 ss16'
bold_font family='monolisa nerd font' style=bold features='calt liga ss01 ss07  ss09 ss11 ss14 ss16'
bold_italic_font family='monolisa nerd font' style='bold italic' features='calt liga ss01 ss07 ss09 ss11 ss14 ss16'
font_size 11.0

# ======================== Window ========================
hide_window_decorations yes
# initial_window_width 900
# initial_window_height 600
# remember_window_size no
# confirm_os_window_close 0

# ======================== Misc ========================
scrollback_lines 200000
map ctrl+shift+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
enable_audio_bell no

# ======================== Scrolling ========================
map ctrl+shift+up scroll_line_up
map ctrl+shift+k scroll_line_up
map ctrl+shift+down scroll_line_down
map ctrl+shift+j scroll_line_down
