profile=high-quality

sub-auto=all
sub-file-paths=sub:subtitles
sub-font='SF Pro Text'
sub-font-size=44
sub-border-size=1
sub-color='#CDCDCD'
sub-shadow=3
sub-shadow-color='#000000'
sub-shadow-offset=2

osc=no

[Idle]
profile-cond=p["idle-active"]
profile-restore=copy-equal
title=' '
keepaspect=no
background=1
