[mgr]
prepend_keymap = [
    { on = "<Esc>",      run = "quit",                          desc = "Exit the process" },
    { on = [ "?" ],      run = "help",                          desc = "Help" },
    { on = [ "g", "d" ], run = "cd ~/Desktop/",                 desc = "Goto ~/Desktop" },
    { on = [ "c", "a" ], run = "plugin compress",               desc = "Archive selected files" },
    { on = [ "c", "p" ], run = "plugin compress -p",            desc = "Archive selected files (password)" },
]
