"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[manager.prepend_keymap]]
on   = [ "g", "v" ]
run  = "cd ~/Videos"
desc = "Goto ~/Videos"

[[manager.prepend_keymap]]
on   = [ "g", "w" ]
run  = "cd ~/Workspace"
desc = "Goto ~/Workspace"

[[manager.prepend_keymap]]
on   = [ "g", "m" ]
run  = "cd ~/Music"
desc = "Goto ~/Music"

[[manager.prepend_keymap]]
on   = [ "g", "n" ]
run  = "cd ~/.config/nvim/lua/plugins/"
desc = "Goto nvim config"

[[manager.prepend_keymap]]
on   = [ "g", "D" ]
run  = "cd ~/Documents/"
desc = "Goto ~/Documents"

[[manager.prepend_keymap]]
on   = [ "g", "o" ]
run  = "cd ~/Obsidian/Second Brain/"
desc = "Goto ~/Obsidian"

[[manager.prepend_keymap]]
on   = [ "?" ]
run  = "help"
desc = "Help"
