[mgr]
show_hidden = true

[opener]
play = [
	{ run = 'open -a "iina" "$@"', orphan = true, for = "unix" },
]

[plugin]
prepend_previewers = [
    # Piper
    { name = "*.md",      run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
    { name = "*/",        run = 'piper -- eza -TL=4 --color=always --icons=always --group-directories-first --no-quotes "$1"' },
    { name = "*.tar*",    run = 'piper --format=url -- tar tf "$1"' },
]
